spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # serverTimezone可以设置为北京时间GMT%2B8、上海时间Asia/Shanghai或者香港时间HongKong
    url: jdbc:mysql://192.168.248.129:3306/myblog?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: luoweihua666...

mybatis:
  type-aliases-package: com.hua.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*.xml

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

